version: '3'

services:
  code-runner:
    build: 'code-runner/.'
    image: 'code-runner'
    ports:
      - '8079:8079'
    networks:
      - hello-compsci-network
    container_name: 'code-runner'

  hello-compsci:
    build: 'frontend-server/.'
    image: 'hello-compsci'
    ports:
      - '8080:8080'
    networks:
      - hello-compsci-network

networks:
  hello-compsci-network: