version: '2'

services:
  code-runner:
    build: 'code-runner/.'
    image: 'code-runner'
    ports:
      - '8079:8079'
    networks:
      - hello-class-network
    container_name: code-runner
    # 5 gb limit
    mem_limit: 5000000000

  hello-class:
    build: 'frontend-server/.'
    image: 'hello-class'
    ports:
      - '8080:8080'
    networks:
      - hello-class-network

networks:
  hello-class-network:
