version: '3'

services:
  code-runner:
    build: 'code-runner/.'
    image: 'code-runner'
    ports:
      - '8079:8079'
    networks:
      hello-compsci-network:
        aliases:
          - code-runner
    container_name: 'code-runner'

  hello-compsci:
    build: 'frontend-server/.'
    image: 'hello-compsci'
    ports:
      - '8080:8080'
    networks:
      hello-compsci-network: 
  
  hcroach:
    image: 'cockroachdb/cockroach:v1.0.5'
    ports:
      - '8000:8080'
      - '26257:26257'
    container_name: 'hcroach'
    volumes:
      - "./database/cockroach-data:/cockroach/cockroach-data"
    entrypoint:
      - /cockroach/cockroach
      - start
      - --insecure
    networks:
      roachnet:
        aliases:
          - hcroach

  hc-database:
    depends_on:
      - hcroach
    build: 'database/.'
    image: 'hc-database'
    ports:
      - '8078:8078'
    networks:
      hello-compsci-network:
        aliases:
          - hc-database
      roachnet:
    container_name: 'hc-database'

networks:
  hello-compsci-network:
  roachnet: