name: hello_class_homepage
description: homepage for Hello, Class!
version: 0.0.1
author: Nick Anderssohn <nicholas.anderssohn@gmail.com>
environment:
  sdk: any
dependencies:
  browser: any
  js: any
  sass: any
  image: any
  simple_streams: any
  hello_class:
    git:
      url: https://github.com/Nick-Anderssohn/hc-dart-lib.git
      ref: master
transformers:
- $dart2js:
    minify: true
- sass
