name: hello_class_homepage
description: homepage for Hello, Class!
version: 0.0.1
author: Nick Anderssohn <nicholas.anderssohn@gmail.com>
environment:
  sdk: any
dependencies:
  browser: any
  js: any
  dart_sass_transformer: any
  image: any
  simple_streams: any
  codemirror: any
  cookie: "0.0.4"
  protobuf: "^0.5.5"
  barback: any
transformers:
- $dart2js:
    minify: true
- dart_sass_transformer
